version: '3.7'

services:
  # 指定服务名称
  account-service:
    # 指定 Dockerfile 所在文件夹的路径。 Compose 将会利用它自动构建这个镜像，然后使用这个镜像。
    build: ./account-svc
    # 使用的镜像
    image: Zh1Cheung/account-svc
    # 环境变量，保存变量到镜像里面，也就是说启动的容器也会包含这些变量设置
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SIGNING_SECRET
      - SENTRY_DSN
      - EMAIL_SERVICE_ENDPOINT
      - COMPANY_SERVICE_ENDPOINT
      - BOT_SERVICE_ENDPOINT
      - INTERCOM_ACCESS_TOKEN
      - ACCOUNT_DATASOURCE_URL
      - ACCOUNT_DATASOURCE_USERNAME
      - ACCOUNT_DATASOURCE_PASSWORD
    # 在使用 Compose 时，最大的好处就是少打启动命令，但是一般项目容器启动的顺序是有要求的，如果直接从上到下启动容器，必然会因为容器依赖问题而启动失败。
    # 例如在没启动数据库容器的时候启动了应用容器，这时候应用容器会因为找不到数据库而退出，
    # 为了避免这种情况我们需要加入一个标签，就是 depends_on，这个标签解决了容器的依赖、启动先后的问题。
    depends_on:
      - bot-service
      - email-service
    # 加入指定网络
    networks:
      - internal_access
      - external_access # db access

  company-service:
    build: ./company-svc
    image: Zh1Cheung/company-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SIGNING_SECRET
      - SENTRY_DSN
      - EMAIL_SERVICE_ENDPOINT
      - ACCOUNT_SERVICE_ENDPOINT
      - BOT_SERVICE_ENDPOINT
      - COMPANY_DATASOURCE_URL
      - COMPANY_DATASOURCE_USERNAME
      - COMPANY_DATASOURCE_PASSWORD
    depends_on:
      - bot-service
      - email-service
    networks:
      - internal_access
      - external_access # db access

  bot-service:
    build: ./bot-svc
    image: Zh1Cheung/bot-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - EMAIL_SERVICE_ENDPOINT
      - ACCOUNT_SERVICE_ENDPOINT
      - COMPANY_SERVICE_ENDPOINT
      - SMS_SERVICE_ENDPOINT
    depends_on:
      - email-service
  #      - sms-svc # commented for demo
    networks:
      - internal_access

  email-service:
    build: ./mail-svc
    image: Zh1Cheung/mail-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - ALIYUN_ACCESS_KEY
      - ALIYUN_ACCESS_SECRET
    networks:
      - internal_access
      - external_access # aliyun access

# commented for demo
#  sms-service:
#    build: ./sms-svc
#    image: sms-svc
#    environment:
#      - SPRING_PROFILES_ACTIVE=test

  whoami-service:
    build: ./whoami-svc
    image: Zh1Cheung/whoami-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - INTERCOM_APP_ID
      - INTERCOM_SIGNING_SECRET
      - ACCOUNT_SERVICE_ENDPOINT
      - COMPANY_SERVICE_ENDPOINT
    depends_on:
      - account-service
      - company-service
    networks:
      - internal_access

# commented for demo
#  ical-service:
#    build: ./ical-svc
#    image: ical-svc
#    environment:
#      - SPRING_PROFILES_ACTIVE=test
#    depends_on:
#      - company-service

  www-service:
    build: ./web-app
    image: Zh1Cheung/www-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
      - ACCOUNT_SERVICE_ENDPOINT
      - COMPANY_SERVICE_ENDPOINT
      - EMAIL_SERVICE_ENDPOINT
      - RECAPTCHA_PUBLIC
      - RECAPTCHA_PRIVATE
    depends_on:
      - account-service
      - company-service
      - email-service
    networks:
      - internal_access

  faraday-service:
    build: ./faraday
    image: Zh1Cheung/faraday-svc
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
    depends_on:
      - account-service
      - company-service
      - www-service
      - whoami-service
#      - ical-service # commented for demo
      - myaccount-service
      - app-service
    networks:
      - internal_access
      - external_access


  myaccount-service:
    build:
      context: ./frontend
      dockerfile: myaccount/Dockerfile
    image: Zh1Cheung/myaccount-spa
    networks:
      - internal_access

  app-service:
    build:
      context: ./frontend
      dockerfile: app/Dockerfile
    image: Zh1Cheung/app-spa
    networks:
      - internal_access

networks:
  internal_access:
    internal: true
  external_access:

